default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  charset: utf8mb4
  collation: utf8mb4_bin
  encoding: utf8mb4

development:
  <<: *default
  database: crawler_development

test:
  <<: *default
  database: crawler_test

production:
  <<: *default
  database: crawler_production
  # FIXME: デプロイ時にridgepoleがRailsをloadしてないためこうしているが、どうにかしたい
  url: <%= YAML.load(`rails credentials:show`)['database_url'] %>

